a = {"added": [],
     "redeemed": [{"deltaCount": 1,
                                "playerLoot": {"asset": "", "count": 0, "disenchantLootName": "", "disenchantValue": 0,
                                               "displayCategories": "COMPANION", "expiryTime": -1, "isNew": false,
                                               "isRental": false, "itemDesc": "", "itemStatus": "NONE",
                                               "localizedDescription": "嗡嗡虫想要接管这个世界——并且吃掉世界中的所有美味珍馐。但，他体型非常小。他不得不时常藏身于别的东西底下，才能不被踩扁。而在藏身期间，他会好好谋划他的复杂计划。",
                                               "localizedName": "蜂魔 嗡嗡虫", "localizedRecipeSubtitle": "",
                                               "localizedRecipeTitle": "", "lootId": "COMPANION_17018",
                                               "lootName": "COMPANION_17018", "parentItemStatus": "NONE",
                                               "parentStoreItemId": -1, "rarity": "LEGENDARY",
                                               "redeemableStatus": "NOT_REDEEMABLE", "refId": "", "rentalGames": 0,
                                               "rentalSeconds": 0, "shadowPath": "",
                                               "splashPath": "/lol-game-data/assets/ASSETS/Loot/Companions/Buglet/Loot_Buglet_Beevil_Tier3.png",
                                               "storeItemId": 17018,
                                               "tags": "3Star,Buglet,EpicColor1,id=d58ee3cf-ec5a-4763-bf00-a46f98c5218f,rarity_legendary",
                                               "tilePath": "/lol-game-data/assets/ASSETS/Loot/Companions/Buglet/Loot_Buglet_Beevil_Tier3.png",
                                               "type": "COMPANION", "upgradeEssenceName": "", "upgradeEssenceValue": 0,
                                               "upgradeLootName": "", "value": 0}}], "removed": [{"deltaCount": 1,
                                                                                                  "playerLoot": {
                                                                                                      "asset": "",
                                                                                                      "count": 1363,
                                                                                                      "disenchantLootName": "",
                                                                                                      "disenchantValue": 0,
                                                                                                      "displayCategories": "CHEST",
                                                                                                      "expiryTime": -1,
                                                                                                      "isNew": false,
                                                                                                      "isRental": false,
                                                                                                      "itemDesc": "",
                                                                                                      "itemStatus": "NONE",
                                                                                                      "localizedDescription": "有概率出现【怪兽来袭】棋盘！",
                                                                                                      "localizedName": "邪恶棋盘魔法引擎",
                                                                                                      "localizedRecipeSubtitle": "",
                                                                                                      "localizedRecipeTitle": "",
                                                                                                      "lootId": "CHEST_3330162",
                                                                                                      "lootName": "CHEST_3330162",
                                                                                                      "parentItemStatus": "NONE",
                                                                                                      "parentStoreItemId": -1,
                                                                                                      "rarity": "DEFAULT",
                                                                                                      "redeemableStatus": "NOT_REDEEMABLE",
                                                                                                      "refId": "",
                                                                                                      "rentalGames": 0,
                                                                                                      "rentalSeconds": 0,
                                                                                                      "shadowPath": "",
                                                                                                      "splashPath": "/lol-game-data/assets/ASSETS/Loot/Companions/Loot_Evil_Whiskers_Chest_small.png",
                                                                                                      "storeItemId": 3330162,
                                                                                                      "tags": "mobile",
                                                                                                      "tilePath": "/lol-game-data/assets/ASSETS/Loot/Companions/Loot_Evil_Whiskers_Chest_small.png",
                                                                                                      "type": "CHEST",
                                                                                                      "upgradeEssenceName": "",
                                                                                                      "upgradeEssenceValue": 0,
                                                                                                      "upgradeLootName": "",
                                                                                                      "value": 0}}]}
