# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FuWenUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FuWen(object):
    def setupUi(self, FuWen):
        FuWen.setObjectName("FuWen")
        FuWen.setWindowModality(QtCore.Qt.NonModal)
        FuWen.setEnabled(True)
        FuWen.resize(594, 869)
        FuWen.setStyleSheet("")

        self.widget_bottom = QtWidgets.QWidget(FuWen)
        self.widget_bottom.setGeometry(QtCore.QRect(100, 60, 431, 731))
        self.widget_bottom.setStyleSheet("QWidget#widget_bottom{\n"
"background-color:#f8f9fa;\n"
"border-radius:10px;\n"
"border: 5px, white;\n"
"margin: 5px;\n"
"}\n"
"")
        self.widget_bottom.setObjectName("widget_bottom")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_bottom)
        self.scrollArea.setGeometry(QtCore.QRect(30, 450, 251, 131))
        self.scrollArea.setStyleSheet("QWidget#scrollAreaWidgetContents_3{\n"
"    background-color:rgb(248, 249, 250);\n"
"\n"
"    border: 1px solid rgb(179, 179, 179) ;\n"
"    border-style:solid;\n"
"\n"
"}\n"
"QWidget#scrollArea{\n"
"     border-width:0px 0px 0px 0px;\n"
"     border-style:solid;\n"
"}\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 251, 131))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.hero_avatar = QtWidgets.QLabel(self.widget_bottom)
        self.hero_avatar.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.hero_avatar.setMaximumSize(QtCore.QSize(100, 100))
        self.hero_avatar.setStyleSheet("")
        self.hero_avatar.setText("")
        self.hero_avatar.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/lol/icon/-1.png"))
        self.hero_avatar.setScaledContents(True)
        self.hero_avatar.setWordWrap(False)
        self.hero_avatar.setObjectName("hero_avatar")
        self.groupBox = QtWidgets.QGroupBox(self.widget_bottom)
        self.groupBox.setGeometry(QtCore.QRect(20, 590, 391, 101))
        self.groupBox.setStyleSheet("QWidget#groupBox{\n"
"        border: 1px solid rgb(179, 179, 179) ;\n"
"        border-style:solid;\n"
"        border-width:1px 1px 1px 1px;\n"
"    \n"
"        border-radius:10px\n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.ui_tips = QtWidgets.QTextBrowser(self.groupBox)
        self.ui_tips.setGeometry(QtCore.QRect(10, 20, 371, 71))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ui_tips.setFont(font)
        self.ui_tips.setStyleSheet("QTextBrowser{\n"
"background-color:#f8f9fa;\n"
"border-width:0px 0px 0px 0px; \n"
"border-style:solid ;\n"
"font: 9pt \"楷体\"\n"
"\n"
"\n"
"}")
        self.ui_tips.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ui_tips.setCursorWidth(6)
        self.ui_tips.setOpenLinks(False)
        self.ui_tips.setObjectName("ui_tips")
        self.line = QtWidgets.QFrame(self.widget_bottom)
        self.line.setGeometry(QtCore.QRect(10, 111, 410, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hero_name = QtWidgets.QLabel(self.widget_bottom)
        self.hero_name.setGeometry(QtCore.QRect(110, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.hero_name.setFont(font)
        self.hero_name.setObjectName("hero_name")
        self.ui_switch_lane = QtWidgets.QComboBox(self.widget_bottom)
        self.ui_switch_lane.setGeometry(QtCore.QRect(330, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ui_switch_lane.setFont(font)
        self.ui_switch_lane.setStyleSheet("QComboBox{\n"
"     border: 2px solid #dadce0;\n"
"    padding: 0 4px;\n"
"    background: rgba(255.000, 255.000, 255.000, 0.000);\n"
"    border-radius:8px;\n"
"}\n"
"QComboBox:focus,\n"
"QComboBox:open {\n"
"    border: 1px solid #0081db;\n"
"}\n"
"QComboBox::item:selected {\n"
"    border: none;\n"
"    background: #4ca6e5;\n"
"    color: #4d5157;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: #ffffff;\n"
"    margin: 0;\n"
"    border: 1px solid #dadce0;\n"
"    selection-background-color: #4ca6e5;\n"
"    selection-color: #4d5157;\n"
"    padding: 2px;\n"
"}\n"
"QComboBox::indicator:checked,")
        self.ui_switch_lane.setCurrentText("")
        self.ui_switch_lane.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.ui_switch_lane.setFrame(False)
        self.ui_switch_lane.setObjectName("ui_switch_lane")
        self.scro_3 = QtWidgets.QScrollArea(self.widget_bottom)
        self.scro_3.setGeometry(QtCore.QRect(20, 120, 390, 301))
        self.scro_3.setMinimumSize(QtCore.QSize(390, 290))
        self.scro_3.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.scro_3.setFont(font)
        self.scro_3.setStyleSheet("QWidget#fuwenlist{\n"
"    background-color:rgb(248, 249, 250);\n"
"    \n"
"\n"
"}\n"
"")
        self.scro_3.setFrameShape(QtWidgets.QFrame.Box)
        self.scro_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scro_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scro_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scro_3.setWidgetResizable(True)
        self.scro_3.setObjectName("scro_3")
        self.fuwenlist = QtWidgets.QWidget()
        self.fuwenlist.setGeometry(QtCore.QRect(0, 0, 386, 297))
        self.fuwenlist.setObjectName("fuwenlist")
        self.scro_3.setWidget(self.fuwenlist)
        self.label = QtWidgets.QLabel(self.widget_bottom)
        self.label.setGeometry(QtCore.QRect(40, 430, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_16 = QtWidgets.QLabel(self.widget_bottom)
        self.label_16.setGeometry(QtCore.QRect(280, 450, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_3 = QtWidgets.QLabel(self.widget_bottom)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:/lol-api/lol-api/图层 1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.swith_tier_3 = QtWidgets.QComboBox(self.widget_bottom)
        self.swith_tier_3.setGeometry(QtCore.QRect(110, 70, 51, 31))
        self.swith_tier_3.setStyleSheet("QComboBox{\n"
"     border: 2px solid #dadce0;\n"
"    padding: 0 4px;\n"
"    background: rgba(255.000, 255.000, 255.000, 0.000);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QComboBox:focus,\n"
"QComboBox:open {\n"
"    border: 1px solid #0081db;\n"
"}\n"
"QComboBox::item:selected {\n"
"    border: none;\n"
"    background: #4ca6e5;\n"
"    color: #4d5157;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: #ffffff;\n"
"    margin: 0;\n"
"    border: 1px solid #dadce0;\n"
"    selection-background-color: #4ca6e5;\n"
"    selection-color: #4d5157;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"    width: 0px; \n"
"\n"
"}\n"
"QComboBox::indicator:checked,")
        self.swith_tier_3.setIconSize(QtCore.QSize(38, 38))
        self.swith_tier_3.setObjectName("swith_tier_3")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/lol-api/lol/icon/ranked-mini-crests/bronze.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.swith_tier_3.addItem(icon, "")
        self.swith_tier_3.setItemText(0, "")
        self.swith_tier_3.addItem("")
        self.layoutWidget = QtWidgets.QWidget(self.widget_bottom)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 430, 91, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_bottom)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 70, 232, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hero_gradient = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hero_gradient.setFont(font)
        self.hero_gradient.setObjectName("hero_gradient")
        self.horizontalLayout.addWidget(self.hero_gradient)
        self.hero_ranking = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hero_ranking.setFont(font)
        self.hero_ranking.setObjectName("hero_ranking")
        self.horizontalLayout.addWidget(self.hero_ranking)
        self.hero_win = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hero_win.setFont(font)
        self.hero_win.setObjectName("hero_win")
        self.horizontalLayout.addWidget(self.hero_win)
        self.state = QtWidgets.QLabel(self.widget_bottom)
        self.state.setGeometry(QtCore.QRect(40, 685, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.state.setFont(font)
        self.state.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.state.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.state.setText("")
        self.state.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state.setObjectName("state")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_bottom)
        self.scrollArea_2.setGeometry(QtCore.QRect(280, 470, 111, 111))
        self.scrollArea_2.setStyleSheet("QWidget#scrollAreaWidgetContents_4{\n"
"    background-color:rgb(248, 249, 250);\n"
"\n"
"    border: 1px solid rgb(179, 179, 179) ;\n"
"    border-style:solid;\n"
"    border-bottom-right-radius:10px;\n"
"\n"
"    border-top-right-radius:10px;\n"
"\n"
"}\n"
"QWidget#scrollArea_2{\n"
"     border-width:0px 0px 0px 0px;\n"
"     border-style:solid;\n"
"}\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 111, 111))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 88, 42))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setMaximumSize(QtCore.QSize(40, 40))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/lol/icon/6655.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(40, 40))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/lol/icon/6655.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.layoutWidget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 60, 88, 42))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_21.setMaximumSize(QtCore.QSize(40, 40))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/lol/icon/6655.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_22.setMaximumSize(QtCore.QSize(40, 40))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/lol/icon/6655.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_3.setGeometry(QtCore.QRect(0, 49, 111, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)

        self.retranslateUi(FuWen)
        QtCore.QMetaObject.connectSlotsByName(FuWen)

    def retranslateUi(self, FuWen):
        _translate = QtCore.QCoreApplication.translate
        FuWen.setWindowTitle(_translate("FuWen", "Dialog"))
        self.groupBox.setTitle(_translate("FuWen", "小技巧"))
        self.ui_tips.setHtml(_translate("FuWen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">-在施放</span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#eb6213;\">暗裔利刃(E)</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">时使用【</span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#eb6213;\">暗影冲决</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">】可提升你命中敌人的几率。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">*诸如【</span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#eb6213;\">恶火束链</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">】或你友军的定身效果等控制技能，将有助于你【</span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#eb6213;\">暗裔利刃</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">】的起手。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">*在你确保能够逼迫对方一战时施放【</span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#eb6213;\">大灭</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">】。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">*亚托克斯的攻击非常具有波段性，所以要利用好时间来规避他的命中区域。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">*亚托克斯的【</span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#eb6213;\">恶火束链</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">】在朝着边界或亚托克斯奔跑时会更容易离开。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">*在亚托克斯使用他的终极技能时，保持距离以防止他复活。</span></p></body></html>"))
        self.hero_name.setText(_translate("FuWen", "弗雷尔卓德之心"))
        self.label.setText(_translate("FuWen", "三件套推荐"))
        self.label_16.setText(_translate("FuWen", "技能"))
        self.swith_tier_3.setItemText(1, _translate("FuWen", "新建项目"))
        self.label_11.setText(_translate("FuWen", "使用率"))
        self.label_12.setText(_translate("FuWen", "胜率"))
        self.hero_gradient.setText(_translate("FuWen", " 梯度:T1"))
        self.hero_ranking.setText(_translate("FuWen", "排名:No_1"))
        self.hero_win.setText(_translate("FuWen", "胜率:99.99%"))
