import sys
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap, QImage, QPainter, QPainterPath
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog, QVBoxLayout
from Fuwen import Ui_FuWen
from Lcu import LcuRequest
from PyQt5 import QtCore, QtGui, QtWidgets


class FuWen(QMainWindow, Ui_FuWen):
    def __init__(self, lcu: LcuRequest):
        super(FuWen, self).__init__()
        self.lcu = lcu
        self.setupUi(self)

    def set_hero(self, name, hero):
        self.hero_name.setText(name)
        # self.hero_avatar.setPixmap(QPixmap(QImage.fromData(self.lcu.getdata(hero['squarePortraitPath']).content)))  # 方形头像
        self.hero_avatar.setPixmap(self.round_scr(hero['squarePortraitPath']))  # 圆形头像

    def add_S(self):
        vbox = QVBoxLayout()
        vbox.addWidget(self.fw_ui())
        vbox.addWidget(self.fw_ui())
        vbox.addWidget(self.fw_ui())
        vbox.setContentsMargins(0, 0, 0, 0)
        self.scrollAreaWidgetContents_3.setMaximumSize(440, 140 * 3)
        self.scrollAreaWidgetContents_3.setLayout(vbox)

    def round_scr(self, path):
        pixmapa = QPixmap(QImage.fromData(self.lcu.getdata(path).content))
        pixmap = QPixmap(360, 360)
        pixmap.fill(Qt.transparent)
        painter = QPainter(pixmap)
        painter.setRenderHints(QPainter.Antialiasing | QPainter.SmoothPixmapTransform)  # 一个是平滑，一个是缩放保持比例
        path = QPainterPath()
        path.addEllipse(0, 0, 360, 360)  # 绘制椭圆
        painter.setClipPath(path)
        painter.drawPixmap(0, 0, 360, 360, pixmapa)
        painter.end()
        return pixmap

    def fw_ui(self):
        frame_3 = QtWidgets.QFrame()
        frame_3.setEnabled(True)
        frame_3.setGeometry(QtCore.QRect(250, 240, 381, 121))
        frame_3.setMinimumSize(QtCore.QSize(0, 0))
        frame_3.setMaximumSize(QtCore.QSize(440, 140))
        frame_3.setStyleSheet("")
        frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        frame_3.setLineWidth(10)
        frame_3.setMidLineWidth(0)
        frame_3.setObjectName("frame_3")
        label_49 = QtWidgets.QLabel(frame_3)
        label_49.setGeometry(QtCore.QRect(0, 10, 101, 111))
        label_49.setText("")
        label_49.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/ArcaneComet.png"))
        label_49.setScaledContents(True)
        label_49.setObjectName("label_49")
        horizontalLayoutWidget_10 = QtWidgets.QWidget(frame_3)
        horizontalLayoutWidget_10.setGeometry(QtCore.QRect(120, 60, 101, 51))
        horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        horizontalLayout_15 = QtWidgets.QHBoxLayout(horizontalLayoutWidget_10)
        horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        horizontalLayout_15.setObjectName("horizontalLayout_15")
        label_50 = QtWidgets.QLabel(horizontalLayoutWidget_10)
        label_50.setMaximumSize(QtCore.QSize(45, 45))
        label_50.setText("")
        label_50.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/RelentlessHunter.png"))
        label_50.setScaledContents(True)
        label_50.setObjectName("label_50")
        horizontalLayout_15.addWidget(label_50)
        label_51 = QtWidgets.QLabel(horizontalLayoutWidget_10)
        label_51.setMaximumSize(QtCore.QSize(45, 45))
        label_51.setText("")
        label_51.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/EyeballCollection.png"))
        label_51.setScaledContents(True)
        label_51.setObjectName("label_51")
        horizontalLayout_15.addWidget(label_51)
        pushButton_5 = QtWidgets.QPushButton(frame_3)
        pushButton_5.setGeometry(QtCore.QRect(240, 80, 131, 31))
        pushButton_5.setMouseTracking(False)
        pushButton_5.setObjectName("pushButton_5")
        verticalLayoutWidget_7 = QtWidgets.QWidget(frame_3)
        verticalLayoutWidget_7.setGeometry(QtCore.QRect(250, 30, 111, 51))
        verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        verticalLayout_7 = QtWidgets.QVBoxLayout(verticalLayoutWidget_7)
        verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        verticalLayout_7.setSpacing(0)
        verticalLayout_7.setObjectName("verticalLayout_7")
        label_55 = QtWidgets.QLabel(verticalLayoutWidget_7)
        label_55.setAlignment(QtCore.Qt.AlignCenter)
        label_55.setObjectName("label_55")
        verticalLayout_7.addWidget(label_55)
        label_56 = QtWidgets.QLabel(verticalLayoutWidget_7)
        label_56.setAlignment(QtCore.Qt.AlignCenter)
        label_56.setObjectName("label_56")
        verticalLayout_7.addWidget(label_56)
        horizontalLayoutWidget_11 = QtWidgets.QWidget(frame_3)
        horizontalLayoutWidget_11.setGeometry(QtCore.QRect(250, 0, 111, 34))
        horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        horizontalLayout_17 = QtWidgets.QHBoxLayout(horizontalLayoutWidget_11)
        horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        horizontalLayout_17.setObjectName("horizontalLayout_17")
        label_57 = QtWidgets.QLabel(horizontalLayoutWidget_11)
        label_57.setText("")
        label_57.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/StatModsAdaptiveForceIcon.png"))
        label_57.setScaledContents(True)
        label_57.setObjectName("label_57")
        horizontalLayout_17.addWidget(label_57)
        label_58 = QtWidgets.QLabel(horizontalLayoutWidget_11)
        label_58.setText("")
        label_58.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/StatModsArmorIcon.png"))
        label_58.setScaledContents(True)
        label_58.setObjectName("label_58")
        horizontalLayout_17.addWidget(label_58)
        label_59 = QtWidgets.QLabel(horizontalLayoutWidget_11)
        label_59.setText("")
        label_59.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/StatModsMagicResIcon.MagicResist_Fix.png"))
        label_59.setScaledContents(True)
        label_59.setObjectName("label_59")
        horizontalLayout_17.addWidget(label_59)
        layoutWidget_5 = QtWidgets.QWidget(frame_3)
        layoutWidget_5.setGeometry(QtCore.QRect(80, 0, 171, 61))
        layoutWidget_5.setObjectName("layoutWidget_5")
        horizontalLayout_16 = QtWidgets.QHBoxLayout(layoutWidget_5)
        horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        horizontalLayout_16.setSpacing(0)
        horizontalLayout_16.setObjectName("horizontalLayout_16")
        label_52 = QtWidgets.QLabel(layoutWidget_5)
        label_52.setMaximumSize(QtCore.QSize(50, 50))
        label_52.setText("")
        label_52.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/GatheringStorm.png"))
        label_52.setScaledContents(True)
        label_52.setObjectName("label_52")
        horizontalLayout_16.addWidget(label_52)
        label_53 = QtWidgets.QLabel(layoutWidget_5)
        label_53.setMinimumSize(QtCore.QSize(0, 0))
        label_53.setMaximumSize(QtCore.QSize(50, 50))
        label_53.setText("")
        label_53.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/6361.png"))
        label_53.setScaledContents(True)
        label_53.setObjectName("label_53")
        horizontalLayout_16.addWidget(label_53)
        label_54 = QtWidgets.QLabel(layoutWidget_5)
        label_54.setMaximumSize(QtCore.QSize(50, 50))
        label_54.setText("")
        label_54.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/PresenceOfMind.png"))
        label_54.setScaledContents(True)
        label_54.setObjectName("label_54")
        horizontalLayout_16.addWidget(label_54)
        return frame_3
