# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lolapiUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setEnabled(True)
        Frame.resize(250, 470)
        Frame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_1 = QtWidgets.QWidget(Frame)
        self.widget_1.setEnabled(True)
        self.widget_1.setGeometry(QtCore.QRect(0, 0, 250, 470))
        self.widget_1.setStyleSheet("\n"
"QWidget#widget_1{\n"
"background-color:#f8f9fa;\n"
"border-radius:10px;\n"
"border: 5px, white;\n"
"margin: 5px;\n"
"}\n"
"\n"
"QPushButton#Button_X{\n"
"background-color:#f8f9fa;\n"
"}\n"
"\n"
"QPushButton:hover#Button_X{\n"
"background-color: rgba(181.000, 202.000, 244.000, 0.333);\n"
"}\n"
"QPushButton:pressed#Button_X {\n"
"   padding-right:6px; /*鼠标按下不放时背景颜色*/\n"
"    padding-bottom:3px;\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgba(181.000, 202.000, 244.000, 0.333); /*背景颜色*/\n"
"    color: #3781ea;\n"
"    border:0px solid #dadce0;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(213, 221, 234); /*鼠标悬停时背景颜色*/\n"
"}\n"
"/*注意pressed一定要放在hover的后面，否则没有效果*/\n"
"QPushButton:pressed {\n"
"     padding-right:0px; /*鼠标按下不放时背景颜色*/\n"
"    padding-bottom:0px;\n"
"}\n"
"QLabel#state{\n"
"color:rgb(0, 170, 255);\n"
"}")
        self.widget_1.setObjectName("widget_1")
        self.profile = QtWidgets.QLabel(self.widget_1)
        self.profile.setGeometry(QtCore.QRect(50, 20, 150, 150))
        self.profile.setMinimumSize(QtCore.QSize(150, 150))
        self.profile.setMaximumSize(QtCore.QSize(150, 150))
        self.profile.setStyleSheet("background:rgb(232, 232, 232)")
        self.profile.setText("")
        self.profile.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/4804.jpg"))
        self.profile.setScaledContents(True)
        self.profile.setObjectName("profile")
        self.name = QtWidgets.QLabel(self.widget_1)
        self.name.setGeometry(QtCore.QRect(10, 170, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setAutoFillBackground(False)
        self.name.setTextFormat(QtCore.Qt.AutoText)
        self.name.setScaledContents(True)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.layoutWidget = QtWidgets.QWidget(self.widget_1)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 220, 231, 197))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(35, 0, 35, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.match_query = QtWidgets.QPushButton(self.layoutWidget)
        self.match_query.setEnabled(True)
        self.match_query.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.match_query.setFont(font)
        self.match_query.setObjectName("match_query")
        self.verticalLayout.addWidget(self.match_query)
        self.math_details = QtWidgets.QPushButton(self.layoutWidget)
        self.math_details.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.math_details.setFont(font)
        self.math_details.setObjectName("math_details")
        self.verticalLayout.addWidget(self.math_details)
        self.setting = QtWidgets.QPushButton(self.layoutWidget)
        self.setting.setMinimumSize(QtCore.QSize(0, 35))
        self.setting.setMaximumSize(QtCore.QSize(3333333, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.setting.setFont(font)
        self.setting.setObjectName("setting")
        self.verticalLayout.addWidget(self.setting)
        self.start = QtWidgets.QPushButton(self.layoutWidget)
        self.start.setEnabled(True)
        self.start.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.verticalLayout.addWidget(self.start)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_1)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 411, 231, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.state = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.state.setFont(font)
        self.state.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.state.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.state.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state.setObjectName("state")
        self.horizontalLayout_2.addWidget(self.state)
        self.dial = QtWidgets.QDial(self.layoutWidget1)
        self.dial.setEnabled(False)
        self.dial.setMaximumSize(QtCore.QSize(40, 2222))
        self.dial.setMouseTracking(False)
        self.dial.setAutoFillBackground(False)
        self.dial.setMaximum(100)
        self.dial.setSingleStep(5)
        self.dial.setProperty("value", 0)
        self.dial.setSliderPosition(0)
        self.dial.setWrapping(False)
        self.dial.setNotchTarget(8.7)
        self.dial.setNotchesVisible(False)
        self.dial.setObjectName("dial")
        self.horizontalLayout_2.addWidget(self.dial)
        self.label_3 = QtWidgets.QLabel(self.widget_1)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 150, 150))
        self.label_3.setMinimumSize(QtCore.QSize(150, 150))
        self.label_3.setMaximumSize(QtCore.QSize(150, 150))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:/lol-api/lol/icon/图层 2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.Button_X = QtWidgets.QPushButton(self.widget_1)
        self.Button_X.setGeometry(QtCore.QRect(200, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Button_X.setFont(font)
        self.Button_X.setStyleSheet("")
        self.Button_X.setObjectName("Button_X")
        self.profile.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.name.raise_()
        self.label_3.raise_()
        self.Button_X.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.name.setText(_translate("Frame", "游戏名字"))
        self.match_query.setText(_translate("Frame", "战绩查询"))
        self.math_details.setText(_translate("Frame", "对局详情"))
        self.setting.setText(_translate("Frame", "功能与设置"))
        self.start.setText(_translate("Frame", "启动游戏"))
        self.state.setText(_translate("Frame", "英雄联盟"))
        self.Button_X.setText(_translate("Frame", "X"))
