# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'se_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow, QWidget

from Widget import RoundedWindow


class Ui_Form(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowFlags(
            QtCore.Qt.SplashScreen | QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.WindowTransparentForInput)
        self.setWindowOpacity(0.6)
        self.setAttribute(Qt.WA_TranslucentBackground, True)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(865, 661)
        self.summoner_1 = QtWidgets.QWidget(Form)
        self.summoner_1.setGeometry(QtCore.QRect(0, 0, 331, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.summoner_1.setFont(font)
        self.summoner_1.setStyleSheet("QWidget#summoner_1{\n"
                                      "background-color:rgb(248, 249, 250);\n"
                                      "border: 1px solid rgb(179, 179, 179) ;\n"
                                      "border-style:solid;\n"
                                      "border-bottom-right-radius:10px;\n"
                                      "border-top-right-radius:10px;\n"
                                      "}")
        self.summoner_1.setObjectName("summoner_1")
        self.layoutWidget = QtWidgets.QWidget(self.summoner_1)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.total_sessions = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.total_sessions.setFont(font)
        self.total_sessions.setObjectName("total_sessions")
        self.horizontalLayout.addWidget(self.total_sessions)
        self.total_rate = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.total_rate.setFont(font)
        self.total_rate.setObjectName("total_rate")
        self.horizontalLayout.addWidget(self.total_rate)
        self.total_rank = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_rank.setFont(font)
        self.total_rank.setObjectName("total_rank")
        self.horizontalLayout.addWidget(self.total_rank)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.recently_worl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.recently_worl.setFont(font)
        self.recently_worl.setAlignment(QtCore.Qt.AlignCenter)
        self.recently_worl.setObjectName("recently_worl")
        self.horizontalLayout_3.addWidget(self.recently_worl)
        self.recently_rate = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.recently_rate.setFont(font)
        self.recently_rate.setObjectName("recently_rate")
        self.horizontalLayout_3.addWidget(self.recently_rate)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.hero_sessions = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.hero_sessions.setFont(font)
        self.hero_sessions.setObjectName("hero_sessions")
        self.horizontalLayout_2.addWidget(self.hero_sessions)
        self.hero_rate = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.hero_rate.setFont(font)
        self.hero_rate.setObjectName("hero_rate")
        self.horizontalLayout_2.addWidget(self.hero_rate)
        self.session_value_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.session_value_5.setFont(font)
        self.session_value_5.setObjectName("session_value_5")
        self.horizontalLayout_2.addWidget(self.session_value_5)
        self.hero_worl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hero_worl.setFont(font)
        self.hero_worl.setObjectName("hero_worl")
        self.horizontalLayout_2.addWidget(self.hero_worl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "总:"))
        self.total_sessions.setText(_translate("Form", "9999场"))
        self.total_rate.setText(_translate("Form", "100%"))
        self.total_rank.setText(_translate("Form", "青铜IV34"))
        self.label_4.setText(_translate("Form", "近20场:"))
        self.recently_worl.setText(_translate("Form", "99胜99负"))
        self.recently_rate.setText(_translate("Form", "100%"))
        self.pushButton.setText(_translate("Form", "详情"))
        self.label_3.setText(_translate("Form", "英雄:"))
        self.hero_sessions.setText(_translate("Form", "9999场"))
        self.hero_rate.setText(_translate("Form", "100%"))
        self.session_value_5.setText(_translate("Form", "近期"))
        self.hero_worl.setText(_translate("Form", "99胜99负"))
