# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI_ui code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 731)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 601, 731))
        self.widget.setStyleSheet("QWidget#widget_scrollarea{\n"
"background-color:#f8f9fa;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"#widget_accept,#widget_team,#widget_ban,#widget_career,#widget_grab,#widget_sata,#widget_resource,#widget_start,#widget_room{\n"
"    background-color:rgb(226, 234, 248);\n"
"      \n"
"    border-radius:10px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QWidget#widget{\n"
"background-color:#f8f9fa;\n"
"border-radius:10px;\n"
"margin: 5px;\n"
"}\n"
"QWidget#widget_top{\n"
"/*background-color:rgb(243, 243, 243);*/\n"
"margin: 5px;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton#close_button{\n"
"background-color:rgb(248, 249, 250);\n"
"\n"
"}\n"
"QPushButton {\n"
"    background-color: rgba(181.000, 202.000, 244.000, 0.333); /*背景颜色*/\n"
"    color: #3781ea;\n"
"    border:0px solid #dadce0;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(213, 221, 234); /*鼠标悬停时背景颜色*/\n"
"}\n"
"/*注意pressed一定要放在hover的后面，否则没有效果*/\n"
"QPushButton:pressed {\n"
"     padding-right:0px; /*鼠标按下不放时背景颜色*/\n"
"    padding-bottom:0px;\n"
"}\n"
"\n"
"\n"
"QScrollArea{\n"
"border: 0px solid;\n"
"\n"
"background-color: #f8f9fa;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: #f8f9fa;\n"
"width: 10px;\n"
"\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: Gainsboro;\n"
"min-height: 20px;\n"
"border-radius: 5px;\n"
"border: none;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: 0px solid grey;\n"
"background: #32CC99;\n"
"height: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: 0px solid grey;\n"
"background: #32CC99;\n"
"height: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"width: 0px;\n"
"height: 0px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid red;  \n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:0px;    \n"
"        \n"
"    border-bottom: 1px solid #B3B3B3;     \n"
"    background-color:rgb(0, 0, 0,0);\n"
"    border-color:rgb(190, 190, 195)\n"
"    }\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid rgb(76, 255, 180);\n"
"    }\n"
"/*QCombobox主体*/\n"
"QComboBox {\n"
"    border: 2px solid #f3f3f3;/*设置线宽*/\n"
"    background-color:rgb(209, 217, 230);/*背景颜色*/\n"
"    border-radius:5px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    border-style:solid;/*边框为实线型*/\n"
"    border-width:1px;/*边框宽度*/\n"
"    border-color:rgb(226, 234, 248);/*边框颜色*/\n"
"    padding-left: 10px;/*左侧边距*/\n"
"}\n"
"/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    width: 0px;/*设置按钮范围宽度*/\n"
"}\n"
"\n"
"\n"
"\n"
"/* 下拉后，整个下拉窗体样式 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #f3f3f3;/*边框宽度、线形、颜色*/\n"
"    background-color: rgba(237, 242, 255, 1);/*背景颜色*/\n"
"    border-radius: 15px;/*圆角*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    min-width: 9em;   /*# 组合框的最小宽度*/\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    border-radius: 15px;/*圆角*/\n"
"    height: 30px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"    background-color: rgb(237, 242, 255);\n"
"\n"
"}\n"
"\n"
"/*以下部分不知为何不生效，有待调试*/\n"
"/* 下拉后，整个下拉窗体越过每项的样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #FFFFF0;\n"
"       /* 整个下拉窗体越过每项的背景色 */\n"
"    background-color: rgb(98, 0, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: #FFFFF0;\n"
"    background-color: rgb(0, 85, 200);\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.widget_top = QtWidgets.QWidget(self.widget)
        self.widget_top.setGeometry(QtCore.QRect(0, 0, 601, 61))
        self.widget_top.setStyleSheet("")
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_23.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_21 = QtWidgets.QLabel(self.widget_top)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        self.label_29 = QtWidgets.QLabel(self.widget_top)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.label_28 = QtWidgets.QLabel(self.widget_top)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        spacerItem = QtWidgets.QSpacerItem(352, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(self.widget_top)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_23.addWidget(self.close_button)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 60, 571, 651))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 561, 950))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 950))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget_scrollarea = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_scrollarea.setGeometry(QtCore.QRect(0, 0, 561, 950))
        self.widget_scrollarea.setStyleSheet("")
        self.widget_scrollarea.setObjectName("widget_scrollarea")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_scrollarea)
        self.verticalLayout_10.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout_10.setSpacing(15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_accept = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_accept.setObjectName("widget_accept")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_accept)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.widget_accept)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_21.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radio_accept_on = QtWidgets.QRadioButton(self.widget_accept)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_accept_on.setFont(font)
        self.radio_accept_on.setChecked(True)
        self.radio_accept_on.setAutoRepeat(False)
        self.radio_accept_on.setAutoExclusive(True)
        self.radio_accept_on.setObjectName("radio_accept_on")
        self.horizontalLayout_5.addWidget(self.radio_accept_on)
        self.radio_accept_off = QtWidgets.QRadioButton(self.widget_accept)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_accept_off.setFont(font)
        self.radio_accept_off.setObjectName("radio_accept_off")
        self.horizontalLayout_5.addWidget(self.radio_accept_off)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addWidget(self.widget_accept)
        self.widget_team = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_team.setObjectName("widget_team")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_team)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_27 = QtWidgets.QLabel(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.label_24 = QtWidgets.QLabel(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:rgb(153, 153, 153)")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.radio_team_on = QtWidgets.QRadioButton(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_team_on.setFont(font)
        self.radio_team_on.setChecked(True)
        self.radio_team_on.setObjectName("radio_team_on")
        self.horizontalLayout_19.addWidget(self.radio_team_on)
        self.radio_team_off = QtWidgets.QRadioButton(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_team_off.setFont(font)
        self.radio_team_off.setObjectName("radio_team_off")
        self.horizontalLayout_19.addWidget(self.radio_team_off)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.team_show_my = QtWidgets.QCheckBox(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.team_show_my.setFont(font)
        self.team_show_my.setChecked(True)
        self.team_show_my.setObjectName("team_show_my")
        self.verticalLayout_9.addWidget(self.team_show_my)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_2 = QtWidgets.QLabel(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_20.addWidget(self.label_2)
        self.team_count = QtWidgets.QLineEdit(self.widget_team)
        self.team_count.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.team_count.setFont(font)
        self.team_count.setAlignment(QtCore.Qt.AlignCenter)
        self.team_count.setObjectName("team_count")
        self.horizontalLayout_20.addWidget(self.team_count)
        self.label_30 = QtWidgets.QLabel(self.widget_team)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_20.addWidget(self.label_30)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.verticalLayout_10.addWidget(self.widget_team)
        self.widget_grab = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_grab.setObjectName("widget_grab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_grab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_9 = QtWidgets.QLabel(self.widget_grab)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_22.addWidget(self.label_9)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radio_grab_on = QtWidgets.QRadioButton(self.widget_grab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_grab_on.setFont(font)
        self.radio_grab_on.setObjectName("radio_grab_on")
        self.horizontalLayout_6.addWidget(self.radio_grab_on)
        self.radio_grab_off = QtWidgets.QRadioButton(self.widget_grab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_grab_off.setFont(font)
        self.radio_grab_off.setChecked(True)
        self.radio_grab_off.setObjectName("radio_grab_off")
        self.horizontalLayout_6.addWidget(self.radio_grab_off)
        self.grab_hero = QtWidgets.QComboBox(self.widget_grab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grab_hero.setFont(font)
        self.grab_hero.setEditable(True)
        self.grab_hero.setMinimumContentsLength(12)
        self.grab_hero.setObjectName("grab_hero")
        self.horizontalLayout_6.addWidget(self.grab_hero)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.widget_grab)
        self.widget_ban = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_ban.setObjectName("widget_ban")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_ban)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.label_17 = QtWidgets.QLabel(self.widget_ban)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.radio_ban_on = QtWidgets.QRadioButton(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_ban_on.setFont(font)
        self.radio_ban_on.setObjectName("radio_ban_on")
        self.horizontalLayout_14.addWidget(self.radio_ban_on)
        self.radio_ban_off = QtWidgets.QRadioButton(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_ban_off.setFont(font)
        self.radio_ban_off.setChecked(True)
        self.radio_ban_off.setObjectName("radio_ban_off")
        self.horizontalLayout_14.addWidget(self.radio_ban_off)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.ban_second = QtWidgets.QLineEdit(self.widget_ban)
        self.ban_second.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ban_second.setFont(font)
        self.ban_second.setAlignment(QtCore.Qt.AlignCenter)
        self.ban_second.setObjectName("ban_second")
        self.horizontalLayout_12.addWidget(self.ban_second)
        self.label_20 = QtWidgets.QLabel(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.ban_hero_1 = QtWidgets.QComboBox(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ban_hero_1.setFont(font)
        self.ban_hero_1.setObjectName("ban_hero_1")
        self.horizontalLayout_13.addWidget(self.ban_hero_1)
        self.ban_hero_2 = QtWidgets.QComboBox(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ban_hero_2.setFont(font)
        self.ban_hero_2.setObjectName("ban_hero_2")
        self.horizontalLayout_13.addWidget(self.ban_hero_2)
        self.ban_hero_3 = QtWidgets.QComboBox(self.widget_ban)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ban_hero_3.setFont(font)
        self.ban_hero_3.setObjectName("ban_hero_3")
        self.horizontalLayout_13.addWidget(self.ban_hero_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.verticalLayout_10.addWidget(self.widget_ban)
        self.widget_career = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_career.setEnabled(False)
        self.widget_career.setObjectName("widget_career")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_career)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(153, 153, 153)")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.career_hero = QtWidgets.QComboBox(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.career_hero.setFont(font)
        self.career_hero.setObjectName("career_hero")
        self.horizontalLayout_4.addWidget(self.career_hero)
        self.label_7 = QtWidgets.QLabel(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.hero_skin = QtWidgets.QComboBox(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hero_skin.setFont(font)
        self.hero_skin.setObjectName("hero_skin")
        self.horizontalLayout_4.addWidget(self.hero_skin)
        self.skin_button = QtWidgets.QPushButton(self.widget_career)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.skin_button.setFont(font)
        self.skin_button.setObjectName("skin_button")
        self.horizontalLayout_4.addWidget(self.skin_button)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addWidget(self.widget_career)
        self.widget_room = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_room.setEnabled(False)
        self.widget_room.setObjectName("widget_room")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_room)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.widget_room)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget_room)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(153, 153, 153)")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.widget_room)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.room_id = QtWidgets.QComboBox(self.widget_room)
        self.room_id.setObjectName("room_id")
        self.horizontalLayout_7.addWidget(self.room_id)
        self.room_button = QtWidgets.QPushButton(self.widget_room)
        self.room_button.setObjectName("room_button")
        self.horizontalLayout_7.addWidget(self.room_button)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addWidget(self.widget_room)
        self.widget_sata = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_sata.setEnabled(False)
        self.widget_sata.setObjectName("widget_sata")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_sata)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.widget_sata)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_sata)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(153, 153, 153)")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.widget_sata)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.sata = QtWidgets.QComboBox(self.widget_sata)
        self.sata.setObjectName("sata")
        self.horizontalLayout_10.addWidget(self.sata)
        self.label_16 = QtWidgets.QLabel(self.widget_sata)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.sata_1 = QtWidgets.QComboBox(self.widget_sata)
        self.sata_1.setObjectName("sata_1")
        self.horizontalLayout_10.addWidget(self.sata_1)
        self.sata_2 = QtWidgets.QComboBox(self.widget_sata)
        self.sata_2.setObjectName("sata_2")
        self.horizontalLayout_10.addWidget(self.sata_2)
        self.sata_3 = QtWidgets.QComboBox(self.widget_sata)
        self.sata_3.setObjectName("sata_3")
        self.horizontalLayout_10.addWidget(self.sata_3)
        self.sata_button = QtWidgets.QPushButton(self.widget_sata)
        self.sata_button.setObjectName("sata_button")
        self.horizontalLayout_10.addWidget(self.sata_button)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_10.addWidget(self.widget_sata)
        self.widget_resource = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_resource.setEnabled(False)
        self.widget_resource.setObjectName("widget_resource")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_resource)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.widget_resource)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.widget_resource)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:rgb(153, 153, 153)")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_resource)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_17.addWidget(self.pushButton_5)
        self.label_26 = QtWidgets.QLabel(self.widget_resource)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_17.addWidget(self.label_26)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_25 = QtWidgets.QLabel(self.widget_resource)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_16.addWidget(self.label_25)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_resource)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_16.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget_resource)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.verticalLayout_10.addWidget(self.widget_resource)
        self.widget_start = QtWidgets.QWidget(self.widget_scrollarea)
        self.widget_start.setEnabled(False)
        self.widget_start.setObjectName("widget_start")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_start)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_start)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.start_client = QtWidgets.QRadioButton(self.widget_start)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_client.setFont(font)
        self.start_client.setIconSize(QtCore.QSize(22, 16))
        self.start_client.setChecked(False)
        self.start_client.setAutoRepeat(False)
        self.start_client.setAutoExclusive(True)
        self.start_client.setAutoRepeatDelay(100)
        self.start_client.setAutoRepeatInterval(10)
        self.start_client.setObjectName("start_client")
        self.horizontalLayout_15.addWidget(self.start_client)
        self.start_wegame = QtWidgets.QRadioButton(self.widget_start)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_wegame.setFont(font)
        self.start_wegame.setCheckable(True)
        self.start_wegame.setChecked(True)
        self.start_wegame.setObjectName("start_wegame")
        self.horizontalLayout_15.addWidget(self.start_wegame)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem22)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.verticalLayout_10.addWidget(self.widget_start)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_21.setText(_translate("Dialog", "LOLHelper"))
        self.label_29.setText(_translate("Dialog", "-"))
        self.label_28.setText(_translate("Dialog", "工具箱"))
        self.close_button.setText(_translate("Dialog", "×"))
        self.label_8.setText(_translate("Dialog", "自动接受:"))
        self.radio_accept_on.setText(_translate("Dialog", "开启"))
        self.radio_accept_off.setText(_translate("Dialog", "关闭"))
        self.label_27.setText(_translate("Dialog", "队友信息:"))
        self.label_24.setText(_translate("Dialog", "在房间内展示队友信息"))
        self.radio_team_on.setText(_translate("Dialog", "开启"))
        self.radio_team_off.setText(_translate("Dialog", "关闭"))
        self.team_show_my.setText(_translate("Dialog", "显示自己"))
        self.label_2.setText(_translate("Dialog", "统计最近"))
        self.team_count.setText(_translate("Dialog", "20"))
        self.label_30.setText(_translate("Dialog", "局"))
        self.label_9.setText(_translate("Dialog", "秒选英雄:"))
        self.radio_grab_on.setText(_translate("Dialog", "开启"))
        self.radio_grab_off.setText(_translate("Dialog", "关闭"))
        self.label_4.setText(_translate("Dialog", "自动禁用:"))
        self.radio_ban_on.setText(_translate("Dialog", "开启"))
        self.radio_ban_off.setText(_translate("Dialog", "关闭"))
        self.label_19.setText(_translate("Dialog", "等待"))
        self.ban_second.setText(_translate("Dialog", "0"))
        self.label_20.setText(_translate("Dialog", "秒后在禁用"))
        self.label_18.setText(_translate("Dialog", "禁用英雄"))
        self.label_3.setText(_translate("Dialog", "生涯背景:"))
        self.label_5.setText(_translate("Dialog", "可以设置未拥有的皮肤,重新登录也有效"))
        self.label_6.setText(_translate("Dialog", "英雄"))
        self.label_7.setText(_translate("Dialog", "皮肤"))
        self.skin_button.setText(_translate("Dialog", "应用"))
        self.label_10.setText(_translate("Dialog", "创建房间:"))
        self.label_11.setText(_translate("Dialog", "提示"))
        self.label_12.setText(_translate("Dialog", "ID:"))
        self.room_button.setText(_translate("Dialog", "创建"))
        self.label_13.setText(_translate("Dialog", "在线状态:"))
        self.label_14.setText(_translate("Dialog", "重新登录会失效"))
        self.label_15.setText(_translate("Dialog", "状态:"))
        self.label_16.setText(_translate("Dialog", "段位:"))
        self.sata_button.setText(_translate("Dialog", "应用"))
        self.label_22.setText(_translate("Dialog", "资源获取:"))
        self.label_23.setText(_translate("Dialog", "皮肤原画,图标等"))
        self.pushButton_5.setText(_translate("Dialog", "保存至"))
        self.label_26.setText(_translate("Dialog", "C:\\"))
        self.label_25.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_2.setText(_translate("Dialog", "保存"))
        self.pushButton.setText(_translate("Dialog", "全部保存"))
        self.label.setText(_translate("Dialog", "启动方式:"))
        self.start_client.setText(_translate("Dialog", "客户端"))
        self.start_wegame.setText(_translate("Dialog", "WeGame"))
