# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dnf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 794)
        self.widget_1 = QtWidgets.QWidget(Form)
        self.widget_1.setGeometry(QtCore.QRect(160, 60, 711, 541))
        self.widget_1.setStyleSheet("QWidget#Button_X {\n"
"            border-width:0px 0px 0px 0px; \n"
"   \n"
"}\n"
"QWidget#Button_min{\n"
"border-width:0px 0px 0px 0px; \n"
"}\n"
"QWidget#widget_1{\n"
"background-color:#f8f9fa;\n"
"border-radius:10px;\n"
"border: 5px, white;\n"
"margin: 5px;\n"
"}\n"
"QPushButton {\n"
"    color: #0081db;\n"
"    border: 1px solid #dadce0;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:!window {\n"
"    background: transparent;\n"
"}\n"
"QPushButton:flat,\n"
"QPushButton:default {\n"
"    border: none;\n"
"    padding: 5px 9px;\n"
"}\n"
"QPushButton:default {\n"
"    color: #f8f9fa;\n"
"    background: #0081db;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:flat:hover {\n"
"    background: rgba(181.000, 202.000, 244.000, 0.333);\n"
"}\n"
"QPushButton:pressed,\n"
"QPushButton:flat:pressed,\n"
"QPushButton:checked:pressed,\n"
"QPushButton:flat:checked:pressed {\n"
"    background: rgba(181.000, 202.000, 244.000, 0.933);\n"
"}\n"
"QPushButton:checked,\n"
"QPushButton:flat:checked {\n"
"    background: rgba(181.000, 202.000, 244.000, 0.733);\n"
"}\n"
"QPushButton:default:hover {\n"
"    background: #3781ea;\n"
"}\n"
"QPushButton:default:pressed {\n"
"    background: #6ca1f0;\n"
"}\n"
"QPushButton:default:disabled {\n"
"    background: #dadce0;\n"
"}\n"
"QRadioButton {\n"
"    spacing: 8px;\n"
"}\n"
"QGroupBox::title,\n"
"QAbstractItemView::item {\n"
"    spacing: 6px;\n"
"}\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator,\n"
"QAbstractItemView::indicator,\n"
"QRadioButton::indicator {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"}\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator,\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,\n"
"QGroupBox::indicator:unchecked:disabled,\n"
"\n"
"QCheckBox::indicator:checked,\n"
"QGroupBox::indicator:checked,\n"
"\n"
"QCheckBox::indicator:checked:disabled,\n"
"QGroupBox::indicator:checked:disabled,\n"
"\n"
"QCheckBox::indicator:indeterminate,\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled,\n"
"\n"
"")
        self.widget_1.setObjectName("widget_1")
        self.button_count = QtWidgets.QPushButton(self.widget_1)
        self.button_count.setGeometry(QtCore.QRect(540, 450, 81, 41))
        self.button_count.setObjectName("button_count")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget_1)
        self.groupBox_7.setGeometry(QtCore.QRect(350, 30, 281, 291))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(110, 10, 61, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/BaKa/output/sprite_character_priest_effect.NPK/atskillicon.img/84.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox.setGeometry(QtCore.QRect(20, 160, 241, 111))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 63, 141, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.jt_show_zsg = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.jt_show_zsg.setFont(font)
        self.jt_show_zsg.setObjectName("jt_show_zsg")
        self.horizontalLayout.addWidget(self.jt_show_zsg)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 70, 77, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.jt_show_zsg_cj = QtWidgets.QLabel(self.layoutWidget1)
        self.jt_show_zsg_cj.setMinimumSize(QtCore.QSize(50, 20))
        self.jt_show_zsg_cj.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.jt_show_zsg_cj.setFont(font)
        self.jt_show_zsg_cj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jt_show_zsg_cj.setObjectName("jt_show_zsg_cj")
        self.horizontalLayout_2.addWidget(self.jt_show_zsg_cj)
        self.jt_show_zsg_cj_tb = QtWidgets.QLabel(self.layoutWidget1)
        self.jt_show_zsg_cj_tb.setMaximumSize(QtCore.QSize(18, 17))
        self.jt_show_zsg_cj_tb.setText("")
        self.jt_show_zsg_cj_tb.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/x.png"))
        self.jt_show_zsg_cj_tb.setScaledContents(True)
        self.jt_show_zsg_cj_tb.setObjectName("jt_show_zsg_cj_tb")
        self.horizontalLayout_2.addWidget(self.jt_show_zsg_cj_tb)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(160, 30, 77, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.jt_show_sg_cj = QtWidgets.QLabel(self.layoutWidget2)
        self.jt_show_sg_cj.setMinimumSize(QtCore.QSize(50, 20))
        self.jt_show_sg_cj.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.jt_show_sg_cj.setFont(font)
        self.jt_show_sg_cj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jt_show_sg_cj.setObjectName("jt_show_sg_cj")
        self.horizontalLayout_4.addWidget(self.jt_show_sg_cj)
        self.jt_show_sg_cj_tb = QtWidgets.QLabel(self.layoutWidget2)
        self.jt_show_sg_cj_tb.setMaximumSize(QtCore.QSize(18, 17))
        self.jt_show_sg_cj_tb.setText("")
        self.jt_show_sg_cj_tb.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/x.png"))
        self.jt_show_sg_cj_tb.setScaledContents(True)
        self.jt_show_sg_cj_tb.setObjectName("jt_show_sg_cj_tb")
        self.horizontalLayout_4.addWidget(self.jt_show_sg_cj_tb)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.jt_show_sg = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.jt_show_sg.setFont(font)
        self.jt_show_sg.setObjectName("jt_show_sg")
        self.horizontalLayout_3.addWidget(self.jt_show_sg)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 241, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(130, 30, 77, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.zj_show_sg_cj = QtWidgets.QLabel(self.layoutWidget_3)
        self.zj_show_sg_cj.setMinimumSize(QtCore.QSize(50, 20))
        self.zj_show_sg_cj.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.zj_show_sg_cj.setFont(font)
        self.zj_show_sg_cj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zj_show_sg_cj.setObjectName("zj_show_sg_cj")
        self.horizontalLayout_8.addWidget(self.zj_show_sg_cj)
        self.zj_show_sg_cj_tb = QtWidgets.QLabel(self.layoutWidget_3)
        self.zj_show_sg_cj_tb.setMaximumSize(QtCore.QSize(18, 17))
        self.zj_show_sg_cj_tb.setText("")
        self.zj_show_sg_cj_tb.setPixmap(QtGui.QPixmap("C:/Users/lnori/Desktop/x.png"))
        self.zj_show_sg_cj_tb.setScaledContents(True)
        self.zj_show_sg_cj_tb.setObjectName("zj_show_sg_cj_tb")
        self.horizontalLayout_8.addWidget(self.zj_show_sg_cj_tb)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.zj_show_sg = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.zj_show_sg.setFont(font)
        self.zj_show_sg.setObjectName("zj_show_sg")
        self.horizontalLayout_7.addWidget(self.zj_show_sg)
        self.button_jc = QtWidgets.QPushButton(self.widget_1)
        self.button_jc.setGeometry(QtCore.QRect(410, 450, 78, 41))
        self.button_jc.setObjectName("button_jc")
        self.line = QtWidgets.QFrame(self.widget_1)
        self.line.setGeometry(QtCore.QRect(300, 30, 20, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget_1)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 180, 231, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 30, 112, 61))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_11.addWidget(self.label_32)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(140, 30, 71, 61))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.jt_zhili = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.jt_zhili.setObjectName("jt_zhili")
        self.verticalLayout_12.addWidget(self.jt_zhili)
        self.jt_lv = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.jt_lv.setObjectName("jt_lv")
        self.verticalLayout_12.addWidget(self.jt_lv)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_1)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 20, 231, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 20, 121, 111))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_9.addWidget(self.label_31)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(140, 20, 71, 111))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.zj_zhili = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.zj_zhili.setObjectName("zj_zhili")
        self.verticalLayout_10.addWidget(self.zj_zhili)
        self.zl_buff = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.zl_buff.setObjectName("zl_buff")
        self.verticalLayout_10.addWidget(self.zl_buff)
        self.zl_lv = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.zl_lv.setObjectName("zl_lv")
        self.verticalLayout_10.addWidget(self.zl_lv)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_1)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 300, 261, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 162, 101))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(180, 30, 71, 101))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sg_guding = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.sg_guding.setObjectName("sg_guding")
        self.verticalLayout_8.addWidget(self.sg_guding)
        self.sg_buff_bxy = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.sg_buff_bxy.setObjectName("sg_buff_bxy")
        self.verticalLayout_8.addWidget(self.sg_buff_bxy)
        self.sg_buff_gh = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.sg_buff_gh.setObjectName("sg_buff_gh")
        self.verticalLayout_8.addWidget(self.sg_buff_gh)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(40, 140, 159, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 170, 231, 26))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sg_bf_1 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.sg_bf_1.setObjectName("sg_bf_1")
        self.horizontalLayout_6.addWidget(self.sg_bf_1)
        self.sg_bf_2 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.sg_bf_2.setObjectName("sg_bf_2")
        self.horizontalLayout_6.addWidget(self.sg_bf_2)
        self.sg_bf_3 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.sg_bf_3.setObjectName("sg_bf_3")
        self.horizontalLayout_6.addWidget(self.sg_bf_3)
        self.sg_bf_4 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.sg_bf_4.setObjectName("sg_bf_4")
        self.horizontalLayout_6.addWidget(self.sg_bf_4)
        self.sg_bf_5 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.sg_bf_5.setObjectName("sg_bf_5")
        self.horizontalLayout_6.addWidget(self.sg_bf_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_count.setText(_translate("Form", "计算"))
        self.groupBox.setTitle(_translate("Form", "进图"))
        self.label_13.setText(_translate("Form", "总三攻:"))
        self.jt_show_zsg.setText(_translate("Form", "99999"))
        self.jt_show_zsg_cj.setText(_translate("Form", "-9999"))
        self.jt_show_sg_cj.setText(_translate("Form", "-9999"))
        self.label_11.setText(_translate("Form", "单BUFF:"))
        self.jt_show_sg.setText(_translate("Form", "99999"))
        self.groupBox_2.setTitle(_translate("Form", "站街"))
        self.zj_show_sg_cj.setText(_translate("Form", "-9999"))
        self.label_18.setText(_translate("Form", "三攻:"))
        self.zj_show_sg.setText(_translate("Form", "99999"))
        self.button_jc.setText(_translate("Form", "设为基础"))
        self.groupBox_6.setTitle(_translate("Form", "进图属性"))
        self.label_15.setText(_translate("Form", " 智    力 :"))
        self.label_32.setText(_translate("Form", "Buff 等 级:"))
        self.groupBox_5.setTitle(_translate("Form", "站街属性"))
        self.label_3.setText(_translate("Form", " 智    力 :"))
        self.label_31.setText(_translate("Form", "基础Buff量:"))
        self.label_5.setText(_translate("Form", "Buff 等 级:"))
        self.groupBox_4.setTitle(_translate("Form", "辟邪玉&&宠物&&光环"))
        self.label_10.setText(_translate("Form", "固定三攻："))
        self.label_12.setText(_translate("Form", "Buff量-辟邪玉 ："))
        self.label_16.setText(_translate("Form", "Buff量-光环 ："))
        self.label_14.setText(_translate("Form", "百分比三攻"))
